### ISSUE TITLE
Rooting a device

### ISSUE THREAD

**Issue by nazimboudeffa** [Flo354/Androick#1]
Hi,
i have a question, don't you think that rooting a device is more dangerous
thx

**Comment by Flo354** [comment]
Hi,

Androïck is only a tool allowing us to analyze the behavior of an android application. 
What she stores ? how ? why ?

Rooting a device is "dangerous" if you don't know what you do, but that doesn't concern my tool, since it is designed for developers/pentesters

**Comment by nazimboudeffa** [comment]
Thx for answering, as jailbreaked iPhones it can really be dangerous to root a smartphone, is there a way for extracting those informations from a smarrtphone without rooting it ?
based on SPF i have an issue for this, you can find it here https://code.google.com/p/splif/
i think that the browser have to be reinstalled with an older version, i didn't try this for now, then accessed with a client side shell as CVE  2010-1759
the problem could be with adb and the access to the shell
