### ISSUE TITLE
"Finding dtabases files" fails

### ISSUE THREAD

**Issue by mfuellbier** [Flo354/Androick#2]
```
$ python2 --version
Python 2.7.14
$ python2 androick.py -A -f [NAME]
packages found with this name :
1) [NAME]
Which packages do you want extract. Ex: 1 3 6 (type 0 to quit) : 1

Verifying if package '[NAME]' exist...
Creating directories...
Downloading APK...

Downloading datas...

Downloading external datas...

Downloading external SD card datas...

downloading libraries files...

Finding databases files...
Traceback (most recent call last):
  File "./androick.py", line 158, in <module>
    main ()
  File "./androick.py", line 154, in main
    package.extract(verbose, datas, sql, key, manifest, permissions, memoryDump)
  File "/home/maikel/pentesttools/Androick/package.py", line 61, in extract
    self.getSQL()
  File "/home/maikel/pentesttools/Androick/package.py", line 237, in getSQL
    mime = magic.Magic()
TypeError: __init__() takes exactly 2 arguments (1 given)
$
```

**Comment by Flo354** [comment]
Hi,

This library had its last commit 4 years ago. I don't maintain it anymore and have no plans to do it.

Saying that, I think that your problem is mostly a dependency problems

> TypeError: __init__() takes exactly 2 arguments (1 given)

It seems that the library you use is not the same as the library used in Androïck.

Hope it helps,

**Comment by mfuellbier** [comment]
Thanks for the fast response anyway. Maybe I will update it and do a pull request.

**Comment by Flo354** [comment]
PR are accepted with pleasure! I just don't have the time to maintain this tool anymore...

**Comment by mfuellbier** [comment]
I fixed the error. It was due to missing dependencies which you correctly provided in the README. So this tool is still working like a charm. The issue can be closed.

**Comment by Flo354** [comment]
Happy to see that the tool still works!

Thanks for your other contribution
